import {
  Rocket,
  Banknote,
  Receipt,
  ShieldCheck,
  Package,
  Boxes,
  Warehouse,
  ShoppingCart,
  ShoppingBasket,
  CreditCard,
  Plug,
  Globe,
  Route,
  Truck,
  Wrench,
  Hammer,
  Factory,
  Handshake,
  Fingerprint,
  Smartphone,
  ClipboardCheck,
  ClipboardList,
  BarChart3,
  Settings,
  Users,
  FileText,
  HelpCircle,
  UtensilsCrossed,
  BedDouble,
  PawPrint,
  Building2,
  type LucideIcon,
} from "lucide-react";

const kbIcons: Record<string, LucideIcon> = {
  Rocket,
  Banknote,
  Receipt,
  ShieldCheck,
  Package,
  Boxes,
  Warehouse,
  ShoppingCart,
  ShoppingBasket,
  CreditCard,
  Plug,
  Globe,
  Route,
  Truck,
  Wrench,
  Hammer,
  Factory,
  Handshake,
  Fingerprint,
  Smartphone,
  ClipboardCheck,
  ClipboardList,
  BarChart3,
  Settings,
  Users,
  FileText,
  HelpCircle,
  UtensilsCrossed,
  BedDouble,
  PawPrint,
  Building2,
};

export const KB_ICON_KEYS = [
  "Rocket",
  "Banknote",
  "Receipt",
  "ShieldCheck",
  "Package",
  "Boxes",
  "Warehouse",
  "ShoppingCart",
  "ShoppingBasket",
  "CreditCard",
  "Plug",
  "Globe",
  "Route",
  "Truck",
  "Wrench",
  "Hammer",
  "Factory",
  "Handshake",
  "Fingerprint",
  "Smartphone",
  "ClipboardCheck",
  "ClipboardList",
  "BarChart3",
  "Settings",
  "Users",
  "FileText",
  "HelpCircle",
  "UtensilsCrossed",
  "BedDouble",
  "PawPrint",
  "Building2",
] as const;
export type KbIconKey = (typeof KB_ICON_KEYS)[number];

export function getKbIcon(iconKey: string): LucideIcon {
  return kbIcons[iconKey] ?? Package;
}
